// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://givyoptljhfmriylvcih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpdnlvcHRsamhmbXJpeWx2Y2loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTA0NDYsImV4cCI6MjA2NzQ4NjQ0Nn0.jB3djuogBpOGTI3VFSQeyWdnHwbPfc-MDBarG_gdtBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});